### ISSUE TITLE
Compressing floating point data

### ISSUE THREAD

**Issue by arnikz** [rudi-cilibrasi/classic-complearn#1]
Hi,
Is there a compressor for floating point data? I would like to try NCD on a set of images. Thank you.

**Comment by rudi-cilibrasi** [comment]
There is no compressor that supports floating point data to my knowledge. However it is possible to decompress images (in case they are already compressed) and then use standard compressors like bzip2 or lzma on them.  An example of this is given in http://homepages.cwi.nl/~paulv/papers/cluster.pdf in the handwritten digit recognition example.

**Comment by arnikz** [comment]
@rudi-cilibrasi Thanks for the reference. I just found that there are fpack & funpack floating-point data compressors developed by NASA https://heasarc.gsfc.nasa.gov/fitsio/fpack/adassPoster.pdf
